name: Android Builder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Show env
        run: env

      # TODO: include as gradle property / in build version?
      # TODO: check result
      - name: Extract runner image version
        run: awk 'BEGIN { FS = "=" } ; /^ImageVersion/ { print $2 }' </etc/environment >"${GITHUB_WORKSPACE}/Github_ImageVersion.txt"

      - name: Grant permission to update SDK dir
        run: sudo chown "${USER}.${USER}" "${ANDROID_SDK_ROOT}" "${ANDROID_SDK_ROOT}"/*

      - name: Prepare SDK cache overlay
        env:
          TMPDIR: ${{ runner.temp }}
        run: |
          mkdir -p "${TMPDIR}/sdk-overlay/"{merged,upper,work}

      - name: Cache SDK updates
        uses: actions/cache@v1
        env:
          cache-name: cache-sdk-upper
        with:
          path: ${{ runner.temp }}/sdk-overlay/upper
          key: ${{ env.cache-name }}-${{ hashFiles('Github_ImageVersion.txt') }}-${{ hashFiles('app/build.gradle') }}

      - name: Mount SDK cache overlay
        env:
          TMPDIR: ${{ runner.temp }}
        run: |
          sudo mount -t overlay overlay -olowerdir="${ANDROID_SDK_ROOT}",upperdir="${TMPDIR}/sdk-overlay/upper",workdir="${TMPDIR}/sdk-overlay/work" "${TMPDIR}/sdk-overlay/merged"
          sudo chown "${USER}.${USER}" "${TMPDIR}/sdk-overlay/merged"
          ls -la "${TMPDIR}/sdk-overlay/merged/"

      - name: Cache gradle/wrapper
        uses: actions/cache@v1
        env:
          cache-name: cache-gradle-wrapper
        with:
          path: .gradle/wrapper
          key: ${{ env.cache-name }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache gradle/caches
        uses: actions/cache@v1
        env:
          cache-name: cache-gradle-caches
        with:
          path: .gradle/caches
          key: ${{ env.cache-name }}-${{ hashFiles('app/build.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          GRADLE_USER_HOME: .gradle
          ANDROID_SDK_ROOT: ${{ runner.temp }}/sdk-overlay/merged
          ANDROID_HOME: ${{ runner.temp }}/sdk-overlay/merged
        run: ./gradlew --warning-mode all clean build

      - name: Archive APKs
        uses: actions/upload-artifact@v1
        with:
          name: FooPing2-apk
          path: app/build/outputs/apk/

      - name: Unmount SDK cache overlay
        env:
          TMPDIR: ${{ runner.temp }}
        run: |
          sudo umount "${TMPDIR}/sdk-overlay/merged"
          ls -laR "${TMPDIR}/sdk-overlay/upper"
